[BE][Team-13][프레디, Starve] 목업 api 배포
codesquad-members-2021/sidedish pull request #22
Opened 2021-04-23 07:03 UTC by Dae-Hwa

안녕하세요 프레디와 스타브입니다.

작업내용은 아래와 같습니다.

- 샘플 Mockup API 에 있는 데이터 json 파일로 변환하여 관리
  - jack라이브러리 직접 이용하여 json파일 파싱하여 사용
- 기본적인 API 작성
  - http://3.36.66.115/best
  - http://3.36.66.115/main
  - http://3.36.66.115/course
  - http://3.36.66.115/soup
  - http://3.36.66.115/side
  - http://3.36.66.115/detail/{hash}
- NginX에 배포 - http://3.36.66.115/
  - 톰캣 프록시 설정
  - 정적 페이지는 NginX에서 관리하도록 설정
  - <details>
        <summary>서버 설정 코드</summary>
        
        server {
            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;

            server_name localhost;
    
            location / {
                    try_files $uri $uri/ @apachesite;
            }
    
            location ~ \.(css|js|jpg|jpeg|gif|htm|html|swf)$ {
            }
    
            location @apachesite {
                    proxy_set_header X-Real-IP  $remote_addr;
                    proxy_set_header Host $host;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_pass http://127.0.0.1:8081;
            }
            
            # try_files 테스트용
            location /index2 {
                    try_files $uri /index.html;
            }
        }
        
    </details>

- 개발환경과 배포환경 분리
  - dev와 prod로 프로필 나눠서 설정 서로 다르게 관리
  - 현재 dev만 사용

gradle 태스크를 작성하다 잘 안되는 부분이 있었습니다.
아래와 같이 스크립트를 작성하니 빌드시에 해당 스크립트까지 같이 실행이 되는 문제가 발생했습니다.
찾아봐도 해결점을 못찾겠어서 현재 해당 내용은 없앤 상태입니다.
```groovy
task bootRun_prod(type: Task) {
    tasks.bootRun.exec()
}
```
이외에 직접 커맨드라인으로 실행하는 방법도 생각해봤는데, 여러 환경을 함께 지원하거나 모듈로 프로젝트를 열었을 경우 처리하기가 힘들어 포기했습니다.

감사합니다.

2021-04-23 14:00 UTC, ksundong requested changes
안녕하세요! 프레디 & Starve!! 리뷰어 Dion입니다.
Mock API를 정성스럽게 작성해주셨는데, 아쉬운 부분이 많네요.
저도 작년에 비슷한 프로젝트를 진행했던 만큼 제가 프로젝트를 진행했던 경험을 바탕으로 들었던 아쉬운 점을 적어볼게요.

- 데이터를 왜 그대로 가져와서 그대로 사용하는 형태로 정의해주셨나요? 좋지 않은 네이밍이 존재하는 형태인데, 그대로 사용해주신 부분이 의아했습니다.
- Mock API 작성에만 굉장히 많은 시간이 들어간 것 같은데요, 저라면 간단하게 구현 후, 실제 API를 빠르게 구현시작하는 형태로 진행했을 것 같습니다. 실제로도 그렇게 했고요.
- 사실 데이터만 전달하는게 끝이 아니라, API 설계가 들어갔으면 했는데, 아쉽네요.

이건 제가 단순히 아쉬웠던 부분이니, 그대로 진행해주시면 됩니다.

아래의 코멘트 참고해주시고, 궁금한 점이나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으면 언제든 코멘트 남겨주세요. 고생하셨습니다~

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/build.gradle
> +version = ''
버전이 없네요??

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/build.gradle
> +}
이렇게 하지않고도, 외부에서 충분히 profile을 select 해줄 수 있을텐데요..🤔

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/temp/HelloController.java
> +}
안쓰면 지워주세요~

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +    }
```suggestion
    private SampleDataFactory() {
    }
```

빈 body는 비워주는 것이 흔히 사용하는 컨벤션입니다.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        }
예외 포장 좋은데요, Custom예외의 사용을 아끼진 않았으면 좋겠네요!

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        try (InputStream is = new ClassPathResource(jsonFilePath).getInputStream()) {
try-with-resources의 사용 좋습니다.
is는 별로 좋지 않은 네이밍이지만, 흔히 사용되니 넘어가죠~

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
이 ObjectMapper는 호출 될 때마다 새로 생성될텐데, 이를 해결할 방법은 어떤 것이 있을까요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +    }
비슷한 형태가 반복됩니다. 중복 제거를 해볼 수 있겠네요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        }
이 메서드를 `DetailDTO` 에 둔다면 이런 스타일이 될겁니다.

```java
public static DetailDTOBuilder builder() {
    return new DetailDTOBuilder();
}
```

구현해주신 형태도 좋습니다만, 위의 형태도 고려해봐주세요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        }
`DetailDTO.builder()...` 과 같은 형태로 사용할 수 있습니다.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +    public static class Data {
내부 클래스 사용보다는, 외부로 빼주는 것이 좋을 것 같은데요~

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        private List<String> detailSection;
필드가 어떤 순서로 배치된건지 이해하기 어렵네요.
그리고, Collection들은 `null`로 초기화하기 보다는 Empty Collection으로 두는 것이 좋다고 생각합니다.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    private String alt;
alt는 어떤 데이터가 담기나요? 별로 구체적이지 않은 것 같아요.
이렇게 협의가 된건가요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    private Price sPrice;
n과 s도 마찬가지입니다. 별로 좋은 네이밍은 아닌 것 같네요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    }
저는 이런 형태의 구현은 별로 선호하지 않아요.
getter는 getter의 역할을 해야하지, 별도의 조작이 가해진다면, getter가 아니라고 생각합니다.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
> +public class Price {
클래스의 분리 좋습니다.
근데 이건 값 객체로 쓸 용도였나요? `price` 필드를 `final`로 정의해보는건 어떨까요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
> +public class Price {
그리고 단위 테스트도 작성해보기 적절한 클래스 같아보이는데 한 번 도전해보시는 것을 추천합니다.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/BestSidedishController.java
> +        return SampleDataFactory.createBestSidedishes();
매 요청마다 이걸 만드는 형태가 될 것 같은데요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/resources-dev/data.sql
> +INSERT INTO test_table(TEST_VALUE) VALUES ('test')
필요한가요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
이렇게 application properties를 만드는 것이 아닙니다.
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config
여기 참고해서 만들어보세요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +@SpringBootTest
이 애노테이션은 어떨 때 사용하는 걸까요?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    Environment environment;
과연 이게 필요했는지는 의문이네요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +        }
이 로직도 필요없죠 사실?

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +                Arguments.of("H9881", DetailDTOTestResults.H9881)
Case를 좀 더 넣어줍시다!

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    @MethodSource
👍 
다만, MethodSource로 사용하는 메서드는 이름을 바꿔주는게 더 좋을 것 같네요.

2021-04-23 14:00 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/web/sidedish/DetailDTOTestResults.java
> +            "}";
과연 이걸 다 확인하는게 맞을지는 잘 모르겠네요.
그냥 객체 하나 만들어서 ObjectMapper로 만드는게 나았을지도요..

2021-04-26 05:26 UTC, Dae-Hwa commented on be/sidedish-be/build.gradle
> +version = ''
제가 이해도가 떨어져서 그런데, 메인 브랜치에 머지되거나 하는 등의 이유로 버전업이 됐다고 가정했을때, 그 때마다 build.gradle도 수정하는 식으로 관리해줘야하는건가요?

2021-04-26 05:34 UTC, Dae-Hwa commented on be/sidedish-be/build.gradle
> +}
환경별로 아예 파일 관리를 다르게 하고 싶었습니다. 특히 json파일과 같이 개발환경에서만 사용되어야 하는 파일들을 따로 관리를 하고 싶었습니다. 
결론적으로는 빌드하여 서버에 올릴 jar파일 내부에 꼭 필요한 파일과 설정만 배포하고 싶어서 이런 구성을 했습니다.
Spring 내부에서 프로필을 선택하거나 jar 실행 시 프로필을 선택하도록 하지 않은 것은 위와 같이 구성할 수 없다고 판단하여 그렇게 했습니다.

2021-04-26 05:40 UTC, Dae-Hwa commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
https://github.com/codesquad-members-2021/sidedish/pull/22#discussion_r619984231
위 내용에 이어지는 내용같아 커맨트 링크를 걸었습니다.

application properties를 이렇게 만들면 안 된다고 하셨는데, 이해도가 떨어지다보니 공식 문서만을 봐서는 왜 그런지 유추하기가 힘든 것 같습니다.

gradle 스크립트로 빌드 시 패키징할 자원을 선택하는건 좋지 않은 방법인건가요?

2021-04-26 08:45 UTC, Dae-Hwa commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
https://github.com/codesquad-members-2021/sidedish/pull/33#discussion_r619667076 이렇게 코맨트 남겨 주신걸 봐서 다시 생각해봤습니다.
war배포가 아니니 jndi는 의미가 없을 것 같고, 암호화도 결국 소스에 비밀번호가 포함되니 옳은 방법은 아닌 것 같습니다.
그렇다면 서버에 미리 계정정보가 담긴 파일같은걸 넣어두고 그걸 읽어올 수 있도록 경로설정을 해주는 방식으로 구현하는게 현재로서 최선일 것 같은데 혹시 이런 접근이 맞는것인가요?

2021-04-26 09:22 UTC, ksundong commented on be/sidedish-be/build.gradle
> +version = ''
그건 정하기 나름이죠~
정답은 없습니다.

2021-04-26 09:26 UTC, ksundong commented on be/sidedish-be/build.gradle
> +}
저는 한 번도 안해봤던 고민이네요. 어떤 의도로 작성하신건지 알 것 같아요.
- 개발환경에서만 사용되는 파일은 gitignore에 등록하면 되지 않나요? 빌드는 정석대로라면 빌드서버를 따로 두고 빌드를 하는게 맞으니까요.

2021-04-26 13:05 UTC, ksundong commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
> [#22 (comment)](https://github.com/codesquad-members-2021/sidedish/pull/22#discussion_r619984231)
> 위 내용에 이어지는 내용같아 커맨트 링크를 걸었습니다. 저런 이유로 gradle과 resource 디렉토리 및 application.properties를 이와 같이 구성했는데요.
> 
> gradle 스크립트로 빌드 시 패키징할 자원을 선택하는건 좋지 않은 방법인건가요?
> 
> application properties를 이렇게 만들면 안 된다고 하셨는데, 이해도가 떨어지다보니 공식 문서만을 봐서는 왜 그런지 유추하기가 힘든 것 같습니다.

일단, 너무 지엽적인 부분이라고 생각이 됩니다. 배포 물론 중요한데, Application 개발이 먼저라고 생각되네요.

제 생각에는, build script로 제외할 만큼의 리소스가 없다고 생각됩니다.
좋다, 좋지 않다의 판단이라기 보다는, '그럴 필요가 없다.' 정도로 생각해주시면 되겠습니다.
패키징 된 파일을 배포할게 아닌이상에야 json 파일이 있고 없고는 큰 의미가 없다고 생각합니다.

공식문서를 보여드린 이유는, Spring에서도 패키지 분리를 염두에 두고 있지 않은 것 같기 때문입니다. 만약 개별 packaging이 필요한 경우 직접 구현해라~ 정도일 것이고, 일반적으로는 한 패키지를 실행할 때, 환경변수를 지정해 실행하는 것이 일반적입니다.
application.properties는 경로를 분리하지 않고 사용하는 것이 일반적이기에, 필요하다면 필요한 리소스만 별도로 패키징 로직을 타는게 맞다고 판단됩니다.

2021-04-26 13:09 UTC, ksundong commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
> [#33 (comment)](https://github.com/codesquad-members-2021/sidedish/pull/33#discussion_r619667076) 이렇게 코맨트 남겨 주신걸 봐서 다시 생각해봤습니다.
> war배포가 아니니 jndi는 의미가 없을 것 같고, 암호화도 결국 소스에 비밀번호가 포함되니 옳은 방법은 아닌 것 같습니다.
> 그렇다면 서버에 미리 계정정보가 담긴 파일같은걸 넣어두고 그걸 읽어올 수 있도록 경로설정을 해주는 방식으로 구현하는게 현재로서 최선일 것 같은데 혹시 이런 접근이 맞는것인가요?

이 역시도 맞다. 맞지 않다로 분리될 수 있는 것이 아닙니다. ㅎㅎ DB 접속정보를 제공하는 많은 방법이 있겠죠.
중요한 것은 하면 안되는 일을 하지 않는 것이라고 생각합니다.

즉, 말씀하신 대로 비밀번호는 노출되지 않아야 하고, 이를 지키는 방향으로 구현해주시면 됩니다.

2021-04-26 13:23 UTC, Dae-Hwa commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
정답이 없는 문제라 많이 어려운 것 이었네요 ㅎㅎ.. 
저희 둘 다 엔진엑스를 처음 써보다 보니 서버를 띄워보는 것을 목표로 했더니 너무 지엽적인 부분들에 신경을 많이 써버린 것 같기도 하네요
말씀해주신 부분들 참고해서 다시 한 번 생각해보겠습니다! 자세히 알려주셔서 감사합니다!!

2021-04-26 13:25 UTC, Dae-Hwa commented on be/sidedish-be/build.gradle
> +}
말씀해주신 부분이 맞긴한데, 배포 시에 숨기고 싶은 자원(json파일이나 sql파일 등)도 공유가 됐으면 해서 이런 선택을 했습니다. 
아래에 답변 주신 부분과 함께 생각해보겠습니다!

2021-04-28 05:06 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        }
추가해줬습니다! 3f7d131

2021-04-28 05:08 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +    public static class Data {
분리했습니다!
8a8bdca

2021-04-28 05:08 UTC, Jiwon-JJW commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        }
Custom예외를 두 개로 만들어 처리 진행 했습니다!
다만 각각 다른 상황에서 발생하는 예외라고 생각되어 두 개로 만들었는데, 하나로 하는게 더 나은 방향인지 궁금합니다..!

2021-04-28 05:08 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        private List<String> detailSection;
empty list로 초기화해줬습니다
530f271

2021-04-28 05:11 UTC, Jiwon-JJW commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
ObjectMapper를 static 변수로 새로 생성하여 이를 해결해 보았습니다!
[c7b3174](https://github.com/codesquad-members-2021/sidedish/pull/22/commits/c7b317444bb5a68cd45cd79363372e88fa1eeec6)

2021-04-28 05:14 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    }
지금 상황에서 이렇게 구현하지 않으면, 생성자와 setter에 모두 해당 소스가 들어가야돼서 이런 식으로 구현했던 것 같습니다.
엔티티 객체들이 구현되면 자연스럽게 해결될 것 같은데, 말씀해주신 부분 꼭 생각하며 진행해보겠습니다 감사합니다!

2021-04-28 05:20 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
> +public class Price {
final로 변경해줬습니다! 436c959

2021-04-28 05:22 UTC, Jiwon-JJW commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +                Arguments.of("H9881", DetailDTOTestResults.H9881)
케이스 입력 진행했습니다! 감사합니다!
283cb52

2021-04-28 05:22 UTC, Dae-Hwa commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    Environment environment;
제거했습니다! 4eea66b33d4bfb0f1a43be7e98f951804eeea5c0

2021-04-28 05:22 UTC, Dae-Hwa commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +        }
제거했습니다!

2021-04-28 05:23 UTC, Dae-Hwa commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +@SpringBootTest
스프링의 컨텍스트가 필요할 때 사용하는 것인데, 필요없어졌기 때문에 제거해줬습니다

2021-04-28 05:23 UTC, Dae-Hwa commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    @MethodSource
be87641 변경해줬습니다!

2021-04-28 05:26 UTC, Dae-Hwa commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
디렉토리 구조를 기본설정으로 돌려줬습니다.
resources 안에 application.properties를 넣어주고, application-default, application-prod 와 같이 프로필에 따라 프로퍼티 파일을 선택할 수 있도록 해줬습니다.
DB접속정보는 소스에 담아두지 않고, 프로젝트 루트(java 실행 위치)에 있는 dbcofig.properties로 읽어오도록 했습니다. 따라서 깃에 함께 담기지 않고, 서버에 미리 가져다 놓고 사용할 예정입니다.

2021-04-28 05:31 UTC, Jiwon-JJW commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +    }
말씀대로 중복제거를 최대한 진행해보았습니다!
26ff085

2021-04-28 05:32 UTC, Jiwon-JJW commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/temp/HelloController.java
> +}
지워주었습니다! 567dac1

2021-04-28 05:40 UTC, Dae-Hwa commented
> 안녕하세요! 프레디 & Starve!! 리뷰어 Dion입니다.
> Mock API를 정성스럽게 작성해주셨는데, 아쉬운 부분이 많네요.
> 저도 작년에 비슷한 프로젝트를 진행했던 만큼 제가 프로젝트를 진행했던 경험을 바탕으로 들었던 아쉬운 점을 적어볼게요.
> 
> * 데이터를 왜 그대로 가져와서 그대로 사용하는 형태로 정의해주셨나요? 좋지 않은 네이밍이 존재하는 형태인데, 그대로 사용해주신 부분이 의아했습니다.
> * Mock API 작성에만 굉장히 많은 시간이 들어간 것 같은데요, 저라면 간단하게 구현 후, 실제 API를 빠르게 구현시작하는 형태로 진행했을 것 같습니다. 실제로도 그렇게 했고요.
> * 사실 데이터만 전달하는게 끝이 아니라, API 설계가 들어갔으면 했는데, 아쉽네요.
> 
> 이건 제가 단순히 아쉬웠던 부분이니, 그대로 진행해주시면 됩니다.
> 
> 아래의 코멘트 참고해주시고, 궁금한 점이나, 도움이 필요한 부분, 이해가 되지 않는 부분, 토론하고 싶은 부분이 있으면 언제든 코멘트 남겨주세요. 고생하셨습니다~

https://github.com/codesquad-members-2021/sidedish/pull/22#discussion_r619211037
https://github.com/codesquad-members-2021/sidedish/pull/22#discussion_r619215309
https://github.com/codesquad-members-2021/sidedish/pull/22#discussion_r619215524

피드백 주신 부분 전체적으로 API설계에 대한 아쉬움을 말씀해주신 것 같아 따로 말씀드리자면,
기본적으로 API를 제공해주는걸 기준으로 개발하기로 협의가 됐습니다. 

말씀해주신대로 좋지 않아보이는 부분들이 있었지만, 그런 부분을 그대로 구현하고 개선하는 방향이 이번 미션의 목표가 아닐까 하는 생각으로 이렇게 진행해봤습니다. 요구사항을 바탕으로 설계해보는 것을 지난 미션에서 수행해봤기 때문에 그런 생각을 해본 것 같습니다.

서버 세팅에 시간이 오래 걸리고 목업 api작성에는 큰 시간이 들지 않았다고 생각하는데, 그래도 말씀해주신 것처럼 적지 않은 시간을 투자한건 맞습니다. 굳이 이렇게 한 이유는 샘플데이터와 기본 테스트케이스 등에 대한 고민을 하지 않아도 될 것이라 생각하였기때문입니다.

아무래도 시간이 많이 촉박하게 느껴지다보니 꼭 해보고 싶은 것들 위주로 학습하며 프로젝트를 진행하다보니 신경쓰지 못했던 부분들이 많이 나온 것 같습니다. 이제 데이터 모델링이 끝났고 구현 단계인데, 다음 pr에서는 더 좋은 설계를 보여드릴 수 있도록 해보겠습니다 감사합니다!

2021-04-28 13:55 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        }
다른 커밋이네요 ㅋㅋ

2021-04-28 13:56 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        }
예외는 여러개 만들어도 상관없고, 둘이 처리가 같다면 같은 부모 예외를 두면 되겠죠?

2021-04-28 13:56 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
스프링에서 제공하는 Bean Factory를 활용해주시는건 어떨까요?

2021-04-28 13:57 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        }
create를 굳이 사용하지 않아도 되겠쬬?

2021-04-28 13:57 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +    public static class Data {
이름까지 잘 바꿔주셨네요.

2021-04-28 13:59 UTC, ksundong commented on be/sidedish-be/src/main/resources-prod/application.properties
> +spring.datasource.initialization-mode=always
서버에 properties를 두어도 좋고, 환경변수로 두어도 됩니다.
방법은 여러가지에요 ㅎㅎ

2021-04-28 14:25 UTC, ksundong approved these changes
고생하셨습니다.
얼마남지 않은 기간동안 많이 발전하셨으면 좋겠네요.
많은 팀들이 제공된 API를 기준으로 개발을 많이 하셨는데, 그 점이 많이 아쉬웠어요.

작년 제가 했던 팀의 repo입니다. https://github.com/codesquad-member-2020/sidedish-03
저희 팀의 문서를 한 번 보시면 좋을 것 같아요. https://github.com/codesquad-member-2020/sidedish-03/wiki/API-Document
그 때 당시에는 여러분들과 같이 REST API에 대한 개념이 부족했어서 Path는 조금 아쉽네요.

항상 최선을 지향하는 형태로 개발해주시는 습관을 들여주시는게 좋습니다. 기존의 관습에 도전해보도록 해봅시다.
요구사항을 바탕으로 설계하는 것은 당연하지만, 요구사항은 언제든 변경가능하다는 점도 생각해보세요!

목업 API는 클라이언트 개발자의 빠른 개발을 위해서도 필요하지만, 목업 API를 토대로 설계의 잘못된 점을 파악하고 수정할 수 있다는 점입니다. 너무 클라이언트 개발자와 약속한 내용이 절대적인 약속이라는 생각을 안하는게 좋을 것 같아요.
사람인 이상 설계가 바뀌고 더 좋은 설계가 생각날 수 있습니다. 다만, Breaking Change를 피할 수 있게끔 해주는 것이 더 중요하겠죠.

이것 역시 정답은 없으니, 해보고 싶은 대로 해보시는 것도 방법이라고 생각됩니다. 고생하셨어요 ㅎㅎ

시간이 촉박하기에 목업에 너무 많은 시간을 사용하신 것 같다는 생각이었습니다. 다음 설계 기대해보겠습니다! 고생하셨습니다~

2021-04-28 14:25 UTC, ksundong commented on .gitignore
> +dbconfig.properties
👍

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/NotParsingJsonFileException.java
> +public class NotParsingJsonFileException extends RuntimeException {
JsonParsingException 정도면 괜찮을 것 같아요.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/NotParsingJsonFileException.java
> +        super("Json파일 파싱 중 에러 발생. jsonFilePath: " + jsonFilePath, e);
하드코드는 상수로 빼는 습관을 들여주세요.
예외 포장을 할 수 있도록 정의해주신 것은 좋네요.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/NotReadJsonFileException.java
> +package com.codesquad.sidedish.utils;
패키지는 다른 곳으로 이동시켜주시는게 좋을 것 같아요.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +            .setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
Bean으로 등록해봅시다.
ObjectMapper를 만들어내는 Factory도 있을거에요.
한 번 찾아보세요~

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +    }
💯

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        return jsonToObject("best-sidedishes", new TypeReference<List<SidedishDTO>>() {
이런 형태로 구현해주신 이유가 있나요? 조금 일반적이진 않은 것 같네요 ㅎㅎ

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        return detailDTOs.stream().collect(Collectors.toMap(DetailDTO::getHash, detailDTO -> detailDTO));
Stream의 사용 좋습니다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +        return jsonToObject("best-sidedishes", new TypeReference<List<SidedishDTO>>() {
여기 존재하는 파일명도 상수로 추출해봅시다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
> +            throw new NotReadJsonFileException(JSON_PATH_PREFIX + jsonFileName + JSON_EXTENSION, e);
`JSON_PATH_PREFIX + jsonFileName + JSON_EXTENSION`
중복되죠?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
> +        return DetailDTOBuilder.create();
생성자를 바로 사용하면 안될까요?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDataDTO.java
> +        return deliveryFee.getFormattedPrice() + " (40,000원 이상 구매 시 무료)";
상수는 추출해줍시다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    }
```suggestion
    @JsonProperty("n_price")
    public String formattednPrice() {
        return nPrice != null ? nPrice.getFormattedPrice() : "";
    }
```

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    }
이런 식의 구현은 어떤가요?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/SidedishDTO.java
> +    private List<ItemDTO> items = Collections.emptyList();
Collections.emptyList()를 사용하면 어떤 List가 생성되나요?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/SidedishDTO.java
> +    private List<ItemDTO> items = Collections.emptyList();
의도하신게 맞나요?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/SidedishDTO.java
> +    private List<ItemDTO> items = Collections.emptyList();
https://www.baeldung.com/java-collections-emptylist-new-list

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
> +            throw new IllegalArgumentException("Error occurred while parsing price, price : " + price, e);
여기도 Custom 예외를 적용할 수 있겠죠?

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
> +    private final long price;
값 객체라면 Equals HashCode도 재정의 해주시길 권장드리겠습니다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/main/resources/application-default.properties
> +spring.config.import=classpath:common.properties
-default를 빼면 default로 동작합니다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    ObjectMapper objectMapper = new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
테스트를 위해서 만들어주신거죠?
사실 이런건 매 테스트 마다 재생성될 필요가 없으니 static final을 사용해 정의해주셔도 좋을 듯 합니다.

2021-04-28 14:25 UTC, ksundong commented on be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
> +    ObjectMapper objectMapper = new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
현재도 재생성되진 않지만, 변경가능하고, 로딩 시점의 차이가 있습니다.

2021-04-28 14:28 UTC, merged

2021-04-28 15:05 UTC, Dae-Hwa commented on be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
> +    }
아... 이런 방법은 생각을 아예 못 해봤네요.. 훨씬 괜찮아 보입니다! 적용해봐야겠어요 ㅎㅎ 감사합니다