[BE][Team-17][Robin, Cooper] 반찬가게 1차 PR 요청드립니다.
codesquad-members-2021/sidedish pull request #24
Opened 2021-04-23 08:18 UTC by pbg0205

안녕하세요. team17의 백엔드 로빈, 쿠퍼입니다.
반찬가게 API 구현 1차 PR 드립니다.😄
아래에 구현 목록 사항과 목업 API 명세서 URL 첨부하여 보내드립니다.
부족한 코드, 시간내어 리뷰해주셔서 감사합니다. 🙇‍♂️ 🙇‍♀️

### 구현 목록 사항
- 베스트 카테고리 기준 전체 상품 목록 조회

- 베스트 카테고리 기준 세부 상품 목록 조회

- 밥찬들 카테고리 기준 세부 상품 목록 조회

### [목업 API 명세서 URL](https://documenter.getpostman.com/view/8052286/TzJuBe2M)

2021-04-24 12:44 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
이번 프로젝트는 스펙 규모가 꽤 되는 거 같네요. 많은 고민 끝에 작성하신 코드 잘 보았습니다.

개선하면 좋을 부분 추려서 피드백 남겨보았는데 확인 부탁드릴게요.

2021-04-24 12:44 UTC, wheejuni commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
> +@RequestMapping("/best")
클라이언트 개발자들과 협의한 거겠지만 그리 좋은 path로 보이진 않습니다.
API인지도 불분명하고, 무엇보다 무엇을 위한 best인지 잘 나타나지 않는 것 같아요.

2021-04-24 12:44 UTC, wheejuni commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
> +    private final ImageService imageService;
우선 이 두 서비스는 아직 사용되지 않는 것 같네요.
그리고 하나의 컨트롤러에 세 개의 서비스나 필요하다면, 컨트롤러가 분리돼야 하는 건 아닌지 고민해 보셔야 할 수도 있겟습니다. 
이미지와 아이템까지 여기서 처리해야 하나요?

2021-04-24 12:44 UTC, wheejuni commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
> +    private BigDecimal sPrice;
`BigDecimal` 사용 좋습니다. 👍 
그러나 `nPrice`, `sPrice` 라는 변수명은 아쉽네요. `n` 과 `s` 에 담긴 의미가 잘 유추되지 않습니다.

2021-04-24 12:44 UTC, wheejuni commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
> +    private BigDecimal s_price;
어떤 경우에도 Java의 코딩 컨벤션에 맞지 않는 변수명을 사용하는 것은 자제해 주시면 좋겠습니다.
만약 JSON response를 위한 커스텀 필드명을 사용하고 싶다면, 아래 링크를 참조해 적절한 애노테이션을 이용하면 됩니다. 

https://www.baeldung.com/jackson-annotations

만약 카멜 케이스 변수명에 대해 일괄적으로 스네이크 케이스를 사용하는 것이 목적이라면, 아래 링크를 보고 학습해 보시는 것도 좋겠습니다. (아래 링크에 담긴 첫번째 솔루션은 권장하지 않습니다)

https://stackoverflow.com/questions/10519265/jackson-overcoming-underscores-in-favor-of-camel-case

2021-04-24 12:44 UTC, wheejuni commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
> +    private final ImageService imageService;
서비스에서 타 서비스에 의존하는 방식은 가급적이면 피해 주시고,
지금 객체 그래프 탐색이 되지않다보니 이 두 엔티티를 조회하는 것이 불가피한 측면이 있어보이는데요,
`ItemRepository` 와 `ImageRepository` 를 바로 주입받는 방향이 더 좋아 보입니다.

2021-04-24 16:31 UTC, pbg0205 commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
> +    private BigDecimal s_price;
위에 참고해주신 내용을 바탕으로 한번 수정해보도록 하겠습니다!

2021-04-24 16:35 UTC, pbg0205 commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
> +    private BigDecimal sPrice;
MockAPI 변수 그대로 사용하는 과정에서 변수명 의미가 불명확하게 선언했네요ㅠ
normalPrice와 salePrice로 변수명 변경하도로 하겠습니다!
피드백 주셔서 감사합니다.😃

2021-04-24 16:38 UTC, pbg0205 commented on backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
> +    private final ImageService imageService;
리팩토링 과정에서 삭제하지 못한 의존성 주입입니다ㅠ 변경하도록 하겠습니다!!

2021-04-28 08:55 UTC, pbg0205 commented
리뷰해주신 부분에 대해서 수정 완료하였습니다!
급하게 프로젝트 진행하는 과정에서 리뷰 사항 외에 추가 기능 구현 내용이 반영되었습니다ㅠ
이 점 유의하셔서 확인 부탁드립니다.
다시 한번 시간내서 리뷰해주신 점 감사드립니다. 😄

2021-04-29 12:39 UTC, merged