[Team15 - BE] 1주차 PR
codesquad-members-2021/sidedish pull request #33
Opened 2021-04-24 09:46 UTC by Seohyoung

안녕하세요 team15 우디 트리입니다!

### 클래스 명 네이밍 문제
- 현재 구현한 로직에서는 필요한 데이터만 추출해서 response 할 수 있도록 DTO를 만들어서 구현하였습니다.
- 저희가 명명, 사용한 DTO가 사실 DAO인지 아니면 Entity인지 궁금합니다.

### [ API 관련 참고사항 ]
- 제공된 Mock API를 기준으로 만들었습니다
- 현재 밥찬들(main, soup, side)에 대한 url 매핑을 아래와 같이 구현했습니다.
  - `@GetMapping("/main")`, `@GetMapping("/soup")`, `@GetMapping("/side")`
  -  원래는 `@PathVariable`로 밥찬들을 포괄할 수 있게 메소드 한 개만 구현을 해놨으나, `@GetMapping("/best")` 와 겹치는 문제가 발생하여 각각의 메소드로 나누어준 상태입니다.
  - 프론트와 협의해서 이후 ItemController에 공통 url(ex, `/dish/main`)을 만들어서 `@GetMapping("dish/{section_name}")`로 통합할 예정입니다. 이 점 참고해주세요!!

2021-04-24 14:54 UTC, ksundong requested changes
안녕하세요! Tree & Woody! 리뷰어 Dion 입니다~
두 번째 프로젝트가 생각보다 어렵게 느껴지는 것 같습니다. 설계도 그렇고, 이미 내려진 API의 형태를 그대로 따라가는 형태가 나오고 있네요.

자, 질문드리겠습니다. 우리가 만약에 위치 정보를 얻기 위해서 외부의 API를 사용한다면, 그 API가 위도 경도를 latitude, hardness 같은 식으로 준다고 하더라도, 그대로 사용하실건가요?
또, API는 결국 Interface입니다. 변경사항에 의해 Client가 변경되는 일은 최대한 줄여야 합니다. 변경 가능성이 적은 설계를 항상 염두에 두는 것이 중요합니다.

## 질문에 대한 답변

현재 구현한 로직에서는 필요한 데이터만 추출해서 response 할 수 있도록 DTO를 만들어서 구현하였습니다.  
저희가 명명, 사용한 DTO가 사실 DAO인지 아니면 Entity인지 궁금합니다.

자, 일단 용어를 사용하기에 앞서서 용어를 이해하고 사용해야합니다. 자신이 사용한 용어조차 모른다면, 대화가 불가능하지 않을까요?

- DTO는 무엇인가요?
- DAO는 무엇인가요?
- Entity는 무엇인가요?
- Domain은 무엇일까요?

이 대답을 제가 해드리는건 도움이 되지 않을 것 같습니다. 직접 찾아보시고, 코멘트 남겨주세요.
그 후에 무엇이 무엇인지에 대해서 더 얘기를 해볼 수 있을 것 같습니다.

## 리뷰

- API Path가 아쉽습니다. 더 좋은 Path를 고민해봅시다.
- Breaking Change가 발생하지 않을 수 있는 API 설계도 고민해봅시다.
- `Best`라는 클래스의 존재 의의가 무엇인지 궁금합니다. 단순 name을 저장하기 위한건가요?
- naming에 있어서 아쉬운 부분이 있습니다. 꼭 개선해주셨으면 좋겠네요.
- 작성하신 코드의 N + 1 쿼리문제는 개선할 방법을 꼭 찾아주세요.
- Custom Exception을 정의해보고, 예외 핸들링까지 해봅시다.

## 참고사항 리뷰

> 원래는 @PathVariable로 밥찬들을 포괄할 수 있게 메소드 한 개만 구현을 해놨으나, @GetMapping("/best") 와 겹치는 문제가 발생하여 각각의 메소드로 나누어준 상태입니다.

왜 겹칠까요? 겹치는 이유를 반드시 생각해봅시다. 겹쳐선 안되는 것들 아닌가요? 잘 생각해봅시다. 놓친게 있을겁니다.

> 프론트와 협의해서 이후 ItemController에 공통 url(ex, /dish/main)을 만들어서 @GetMapping("dish/{section_name}")로 통합할 예정입니다. 이 점 참고해주세요!!

Item이라는 이름이 뭔가 의아하게 느껴지네요. ItemController에서 Dishes를 주는건가요?

---

프로젝트 진행하시느라 고생 많으십니다. 리뷰 한 번 읽어보시고, 적용하고 싶은 부분 적용해주세요~
궁금한 점, 도움이 필요한 부분, 이해가 되지 않는 부분 등은 코멘트 꼭 남겨주세요!

2021-04-24 14:54 UTC, ksundong commented on .gitignore
> +### react ###
전체 공통으로 쓰이는 건가요?
react에 관련된 ignore가 들어있네요?

2021-04-24 14:54 UTC, ksundong commented on backend/.gitignore
> +### react ###
여기도 React에 관련된 것이 들어있네요..?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    @GetMapping("/best")
중복제거가 이뤄지지 않았네요.
또, PR에서도 설명하셨듯, best로 시작하는 것은 적절치 않겠죠~

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public List<BestDTO> showAllBestDishes() {
DTO의 사용 좋네요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public List<BestDTO> showAllBestDishes() {
그런데, 이렇게 리턴하면 다음과 같은 형태가 될겁니다.

``` json
[
  {},
  {}
]
```

이 경우에는 API의 요구사항이 변경될 경우 Breaking Change가 발생하게 됩니다.

```json
"bestDishes": [
  {}
]
```

이런 형태는 추가적인 요구사항이 발생해도, Client에 영향을 미치지 않게되겠죠?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public BestDTO showSingleBestDish(@PathVariable Integer categoryId) {
Integer로 받을 필요가 있을까요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/ItemController.java
> +        logger.info("Show single dish by hash");
debug가 적절해보이네요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/ItemController.java
> +    }
이 구조는 서로가 아무런 관계가 없이 url로 연결되어있습니다.
또한, 하드코딩도 되어있습니다. 개선해볼까요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    private Integer categoryId;
Integer를 사용해주신 이유가 있나요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    private Integer categoryId;
클래스 설계가 조금 독특해보입니다.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    public Best() { }
```suggestion
    public Best() {}
```

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    public Best() { }
빈 생성자를 정의해주신 이유는 무엇인가요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +    public Delivery(){ }
```suggestion
    public Delivery() {}
```
리포맷 해주세요~

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +//    }
사용하지 않는 코드는 바로 제거해주세요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +    private String deliveryType;
뭔가 Type하니까 Enum일 것 같은데, 아닌가보네요~

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +    private String deliveryFee;
Fee가 String 타입인 이유가 있나요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Dish.java
> +    public Dish(){ }
```suggestion
    public Dish() {}
```

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Dish.java
> +    private int sPrice;
네이밍 이렇게 써주시는거 확실한가요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Image.java
> +
nit: 빈 라인도 정리해주는 습관을 들여주세요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("SELECT di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
그냥 JOIN을 쓰면 어떤 JOIN이 되나요?
모두 다 작성해주신건 잘하셨어요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("select di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
section은 사용자의 입력을 받아서 결정되는건가요?
아니라면 과연 LIKE를 써줘야했을지 의문이 듭니다.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +public interface ItemRepository extends CrudRepository<ItemDTO, String> {
왜 DTO가 Repository로 왔을까요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/dto/BestDTO.java
> +    }
정적 팩토리 메서드의 사용 좋네요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/dto/BestDish.java
> +    private Integer category_id;
네이밍은 자바 네이밍 컨벤션을 지켜주세요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private String[] badge;
배열을 써주신 이유가 있나요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private String alt;
alt는 무슨의미인가요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private Integer sPrice;
n_price는 뭐고 s_price는 뭐에요?
이 이름 정말 확실한가요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/service/BestService.java
> +                .map(best -> showSingleBestDish(best.getCategoryId()))
매번 DB를 호출하는 형태인가요?
이건 N + 1 쿼리 아닐까요?

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/service/BestService.java
> +                .collect(Collectors.toList());
음.. 이 코드는 잘 이해가 되지 않네요.
일단 Best라는 클래스가 존재해야하는지 한 번 질문을 던져볼게요.
Best의 name에는 어떤 것이 들어가나요?

그리고 bestRepository에서 무엇을 찾는지 명확하지도 않네요. `findByCategoryId`면 `Best` 들이 나와야 할 것 같은데 `String`이 나오네요.

그리고 매 번 다른 서비스를 호출해서 굉장히 비효율적으로 쿼리가 발생할 것 같은데
이를 해결해보는게 숙제겠네요.

`IllegalArgumentException`도 그냥 던지지 마시고, Custom Exception의 도입을 고려해봐주세요.

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/service/ItemService.java
> +        return itemRepository.findById(hash).orElseThrow(IllegalArgumentException::new);
여기도 Custom Exception 생각해봐주세요~

2021-04-24 14:54 UTC, ksundong commented on backend/src/main/resources/application.properties
> +spring.datasource.password=sidedish
로컬환경도 아닌데 이렇게 노출되는 것은 매우 위험합니다.

2021-04-26 07:36 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("SELECT di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
Inner Join이 됩니다!~ delivery  테이블과 dish 테이블은 1:1 관계라서 Join하였습니다!

2021-04-26 07:38 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Dish.java
> +    private int sPrice;
제공되는 API에서 변형하지 않고, 최대한 구조를 유지하려고 하다 보니 문제가 계속 발생한 것 같습니다ㅠㅠ
위에서 리뷰주신 내용은 조금 더 고민해보고 변경하도록 하겠고,
네이밍도 API 기준으로 작성했는데, 프론트와 협의 후 변경하겠습니다🥲

2021-04-26 07:39 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +    private String deliveryFee;
처음에는 2500원 으로 명시하려고 String으로 사용했는데, int타입으로 값을 전달해주는 것으로 변경하고
DB에만 내용이 반영되었네요~ 모두 Integer 타입으로 변경했습니다!

2021-04-26 07:40 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +    private String deliveryType;
넵 현재는 Enum이 아닌데, 리팩토링 할 여유가 된다면 변경해보겠습니다🙂

2021-04-26 07:43 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    public Best() { }
getter 와 함께 작성했었는데, 우디가 빈 생성자는 JPA와 연관되었다고 알려주어서 학습 후 삭제하였습니다~~

2021-04-26 07:44 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    private Integer categoryId;
Long 타입으로 변경했습니다

2021-04-26 07:53 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public List<BestDTO> showAllBestDishes() {
Dion이 말씀해주신 내용이 약간 이해되지 않아서 제가 이해한 바로 다시 여쭤보겠습니다.
저희가 리턴하는 타입은 List 형식으로 리턴이 되는데, 그런 경우 
Breaking Change (API가 사라지거나 return type 혹은 parameters가 변경되는 경우)에 
유지보수 측면으로 좋은 구조가 아니다라고 이해했는데, 제가 이해한 바가 맞나요??

우선 해당 리턴 타입은 HashMap으로 변경했습니다.

2021-04-26 07:59 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private String alt;
저희가 주어진 API를 그대로 유지하려고 하다보니, 불필요한 부분이더라도 동일한 구조로 만들기 위해서 
작성한 부분과 변수명들이 있습니다. 
금요일 데모 이후에 API를 변경해서 사용한 조들을 보면서 저희도 필요한 부분과 네이밍에 대해서 수정하는 작업이 필요했다고 깨닫고 후회하는 중입니다ㅠㅠ

alt 또한 이 과정의 산물(?)인데요, 결국 title과 동일한 내용이 들어가기 때문에 생성자에서 alt에 title을 대입해주는 방식으로 사용하고 있지만, alt를 굳이 전달하지 않더라도 프론트에서 사용할 수 있는 부분이라서 해당 변수는 삭제하도록 하겠습니다

2021-04-26 08:02 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("select di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
제공된 데이터들을 살펴보니 section이 main이면서 cource인 경우도 있었습니다. 하지만 그런 경우는 1~2개의 케이스밖에 없어서
section을 테이블로 분리하기는 애매하여 String으로 해당하는 section을 모두 받았고
section에 해당하는 정보가 전달되도록 LIKE를 사용했습니다.

2021-04-26 08:02 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Image.java
> +
넵!

2021-04-26 08:04 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private Integer sPrice;
n_price -> normalPrice
s_price -> specialPrice 로 변경했습니다.
@JsonProperty는 카멜케이스가 아닌 스네이크 케이스로 json 키값이 전달되도록 변경하기 위해 사용했습니다!

2021-04-26 09:48 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public List<BestDTO> showAllBestDishes() {
API 가 사라지는건 Breaking Change지만, 이런 경우는 없다고 보셔도 됩니다.
Parameter가 변경되는 경우(예를 들어, bestDishes 말고도 다른 정보가 필요하다던가 하는 경우)에 유지보수 하기가 좋아집니다.
그리고 Map으로 리턴하지말고 DTO를 생성해서 반환해주세요~

2021-04-26 09:49 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    public Best() { }
저희가 쓰는 것은 Spring Data JDBC인데, 한 번 확인해주세요!

2021-04-26 09:49 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Best.java
> +    public Best() { }
아하, 삭제하신거군요.

2021-04-26 09:50 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/Dish.java
> +    private int sPrice;
네네~

2021-04-26 09:50 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("SELECT di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
그러면 JOIN 보다는 INNER JOIN을 써주는게 좋을 것 같습니다~

2021-04-26 09:51 UTC, ksundong commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("select di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
아하 알겠습니다~

2021-04-28 15:12 UTC, ksundong commented
@choitree @jihye-woo 
변경중이신건가요? commit은 계속 올라오는데 Review요청이 없어서 여쭤봅니다.

2021-04-29 03:03 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public BestDTO showSingleBestDish(@PathVariable Integer categoryId) {
Long으로 변경하였습니다!

2021-04-29 03:03 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    public List<BestDTO> showAllBestDishes() {
DTO 타입으로 변경하였습니다.

2021-04-29 03:04 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/controller/BestController.java
> +    @GetMapping("/best")
/best로 두고, main,soup,side를 /section/main , /section/soup, section/side로 하는 방식으로 변경하였습니다.

2021-04-29 03:05 UTC, choitree commented on .gitignore
> +### react ###
리액트 관련된 내용 삭제하였습니다~

2021-04-29 03:06 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/controller/ItemController.java
> +    }
/section/{sectionName}으로 매핑을 변경하고 리팩토링하였습니다!

2021-04-29 03:06 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/Delivery.java
> +//    }
네네!!🙂

2021-04-29 03:12 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +    @Query("SELECT di.`hash` AS `detail_hash`, di.`top_image` AS `image`, de.`delivery_type`, di.`title`, di.`description`, di.`n_price`, di.`s_price`, di.`badge` from dish di JOIN delivery de on di.
INNER JOIN으로 변경하였습니다.

2021-04-29 03:14 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/domain/ItemRepository.java
> +public interface ItemRepository extends CrudRepository<ItemDTO, String> {
DAO로 변경하였습니다!

2021-04-29 03:15 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/dto/BestDish.java
> +    private Integer category_id;
수정하였습니다

2021-04-29 03:17 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/dto/ItemDTO.java
> +    private String[] badge;
badge가 2개인 경우는 2가지 케이스밖에 없기 때문에, event를 별도로 분리하기 보다는 sectionName처럼 한 줄에 두가지 경우를 모두 가지고 있도록 사용하였습니다. DB에서 ,로 작성하고 배열 타입으로 선언하니 , 기준으로 2개가 분리되기에 데이터 가공이 쉽도록 배열로 사용하였습니다.

2021-04-29 03:18 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/service/BestService.java
> +                .map(best -> showSingleBestDish(best.getCategoryId()))
N+1 쿼리를 해결하기 위해서 고민해보았지만, 시간 부족과 해결 방법이 떠오르지 않아 아직 해결하지 못하였습니다ㅠㅠㅠㅠ
우선 구현이 되지 않았던 부분을 추가하고 해당 부분은 추후에 리팩토링해보도록 하겠습니다!

2021-04-29 03:36 UTC, choitree commented on backend/src/main/java/com/team15/sidedish/service/BestService.java
> +                .collect(Collectors.toList());
현재 저희 데이터 구조는 Best 테이블과 Dish 테이블이 별도로 구성되어 있고, Best와 1:1, Dish와 N:1 관계인 Best_Dishes 테이블이 존재합니다. 
Best 클래스는 Best 테이블과 동일하게 categoryId, name에 대한 정보만 존재하고
BestDTO는 Best_Dishes의 데이터를 응답받을 수 있는 구조입니다.

우선 Best_Dishes의 해당 카테고리 아이디가 일치하는 hash값을 List로 받아오고
Best의 이름과 id를 받아온 후
hash값에 맞는 dish를 List 형태로 담아
정적 메소드를 통해 BestDTO의 클래스 형태에 맞게 데이터를 리턴하는 방식으로 구현하였습니다.

디온에게 설명하면서 리팩토링이 가능할 것 같다는 사실을 알게되었네요..!!
이 숙제는..! 추후에 꼭꼭 리팩토링을 해보도록 하겠습니다

2021-04-29 03:46 UTC, choitree commented
디온 재리뷰 요청이 지연된 점 죄송합니다.ㅠㅠ
아직 구현되지 못한 부분과 배포에 시간이 할애되고 있어서 디온이 주신 리뷰 내용에 온전히 집중하기가 어려웠습니다.
리뷰주신 내용에 코멘트를 작성하기 위해 다시 코드를 뜯어(?)보면서 조금 더 간결해질 수 있다는 사실을 인지하였지만 
우선 작동이 되도록 구현하는 저희의 목표를 우선으로 진행하다보니 많은 부분을 놓친 것 같습니다
금일 배포 작업을 진행하고, 명일에 가능하다면 배포와 무관한 브랜치를 만들어 리팩토링하도록 하겠습니다.

디온이 신경써주셨는데 코멘트가 많이 지연된 점 양해 부탁드립니다 :sob:

2021-05-01 06:11 UTC, merged