[Jangbagoony 이노 & MJ] db 스키마 작성, API 구현
codesquad-members-2021/sidedish pull request #34
Opened 2021-04-24 12:04 UTC by eNoLJ

안녕하세요. Jangbagoony팀에 이노, MJ입니다.

현재 스키마를 작성하고 기본적으로 제공되는 API 6개를 구현했습니다. 클라이언트에 최대한 빠르게 API를 제공하기 위해서 새로운 방식으로 API를 만들기보단 안정적인 방법으로 만들다보니 스키마에서는 1:다, 다:다와 같이 관계가 설정되어 있지만 코드 상으로는 매핑하여 사용하지 못했습니다. 이 부분은 추후 공부하여 하나씩 적용할 예정입니다.

지난 프로젝트와는 달리 스키마의 구조가 복잡해졌기 때문에 코드가 너저분한 느낌입니다. 하지만 평소와 마찬가지로 어떤식으로 개선을 해나가야할지 잘 떠오르지가 않네요.
이번에도 많은 조언 부탁드리겠습니다!!
잘부탁드려요ㅎㅎ

클라이언트 배포: http://15.164.68.136/80
서버 배포: http://15.164.68.136/8080
API 문서: https://app.gitbook.com/@todolist-2/s/side-dish

2021-04-25 06:52 UTC, wheejuni requested changes
코드가 너저분한 느낌이 든다면 일단 그것만으로도 더 좋은 코드를 작성할 준비가 된 것입니다. 💯 
그러나 거창한 리팩토링이나 구조 개선을 생각하기 이전에 우선 **기본적으로 지켜야 할 것들을 잘 지키는 일** 에서부터 리팩토링이 출발돼야 할 것입니다. 
반복적인 피드백을 통해 1월달부터 이 점을 항상 강조해 드리고 있습니다. 제 강조의 뜻이 잘 전달되지 않는 것 같아서 개인적으로는 반성을 많이 하고 있습니다. 
코딩의 재미를 느끼고 프로젝트의 공정률을 높이는 것도 의미있지만, 우리가 무엇을 위해 팀 프로젝트를 수행하고 코드 리뷰를 요청하고 있는지도 생각해볼 만 합니다. 
감사합니다.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/domain/Image/Image.java
> +
접근제어자가 하나도 없네요. 인생....

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/domain/dish/Dish.java
> +    Integer bestMenuCategoryId;
`Dish` 안에서 굉장히 많은 필드가 관리되고 있는데요, `@Embeddable` 등을 이용해서 객체 분리를 시도해볼 수 있을 것 같습니다. 
데이터 필드가 많을때는 데이터의 갈래(?) 에 따라 분류하고 분리하는 시도를 해보실 것을 권해 드립니다.

예를 들어 가격 정보라는 갈래 안에서 `nPrice`, `sPrice` 가 분리될 수 있을 것 같고,
`deliveryType`, `deliveryInfo`, `deliveryFee` 등을 따로 분리해서 관리할 수 있을 것 같습니다.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/domain/dish/DishRepository.java
> +    @Query("SELECT * FROM dish ORDER BY rand() LIMIT :limit;")
`ORDER BY rand()` 는 그리 좋은 방법이 아닙니다.
랜덤 인덱스를 서버에서 획득한 후 하나씩 불러오는 방법으로 처리해주세요.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/exception/OrderFailedException.java
> +    }
`EntityNotFoundException` 에서도 비슷한 구현을 하셨던데 이렇게 가면 `ErrorMessage` 를 분리해낸 이점을 별로 살리지 못하는 구현이 됩니다.
오히려 이 예외 클래스에서 `ErrorMessage` 를 필드로 관리하고 `Errormessage` 에 더 많은 정보를 담게 될, 그러니까 기능이 확장될 대비를 하시는 것이 좋겠습니다.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/service/DishService.java
> +    public final CategoryService categoryService;
`Service` 에서 다른 `Service` 에 의존하는 상황은 가급적 없었으면 합니다.
차라리 직접적으로 `ImageRepository` , `BadgeRepository` 등을 주입받는 방향이 더 좋아 보이기는 합니다.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +@CrossOrigin("*")
모든 요청에 대해 CORS를 허용해야 한다면 컨트롤러 이전에 `Filter` 에서 처리하는 방법을 고민해주세요.
_spring cors filter_, _spring mvc cors config_ 등의 검색어로 구글링해보시고 솔루션을 찾아 주세요.

2021-04-25 06:52 UTC, wheejuni commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +        logger.info(categoryId + "번 카테고리의 best 메뉴 요청");
`logger` 에서는 문자열 템플릿을 사용하는 것이 좋다고 리뷰를 충분히 드렸었던 것 같습니다.

```suggestion
        logger.info("{}번 카테고리의 best 메뉴 요청", categoryId);

2021-04-25 13:44 UTC, eNoLJ commented on BE/src/main/java/com/mj_eno/sidedish/domain/Image/Image.java
> +
@wheejuni 와........ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 몰랐습니다. 웃음밖에 안나오네요........
이건 진짜 반성하도록 하겠습니다. 죄송합니다ㅠㅠ
다른 부분도 빠르게 수정하도록 하겠습니다.

2021-04-26 01:07 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +@CrossOrigin("*")
filter에서 처리하면 controller마다 해당 어노테이션을 붙일 필요가 없겠군요!

모든 요청에 대해 CORS를 허용하는 부분은 프런트엔드 개발자의 편의를 위해 임시적으로 적용했습니다. 로컬에서 개발을 마치면 서버의 요청에 대해서만 허용하는 식으로 변경할 예정입니다.

2021-04-26 01:08 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/domain/Image/Image.java
> +
반성합니다... ㅎㅎ...

2021-04-26 01:09 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +        logger.info(categoryId + "번 카테고리의 best 메뉴 요청");
이 부분도 반성합니다... 더 신경 써야겠네요!

2021-04-26 08:12 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/domain/dish/Dish.java
> +    Integer bestMenuCategoryId;
코멘트에 따라 Dish 내에 멤버변수로 있던 부분을 Price와 Delivery 클래스를 선언해서 분리했습니다. 분리하니까 코드의 가독성면에서 많이 개선되었네요~

2021-04-26 08:14 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/domain/dish/DishRepository.java
> +    @Query("SELECT * FROM dish ORDER BY rand() LIMIT :limit;")
코멘트에 따라 관련 내용을 검색하니까 성능 상의 이슈가 있는 것을 확인했습니다. DB에서는 Dish의 id만 조회하고, 자바 코드 상에서 랜덤 id를 선택하여 Dish를 조회하도록 수정했습니다.

2021-04-26 08:18 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/exception/OrderFailedException.java
> +    }
커스텀 예외 클래스에서 ErrorMessage를 멤버변수로 관리하도록 수정했습니다. 그런데 이렇게 수정한 것이 브라이언의 의도와 맞는지 궁금합니다. 더불어 예외 클래스에서 멤버변수로 ErrorMessage를 관리하는 것이 유지보수면에서 어떤 이점이 있는지 잘 이해가 되지 않습니다... 조금 더 구체적으로 설명해주시면 감사하겠습니다 :)

2021-04-26 08:22 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +@CrossOrigin("*")
localhost:3000과 서버의 요청에 대해서만 CORS를 허용하는 식으로 변경했습니다. 코멘트에 따라 filter에서 관련 설정을 하는 것으로 수정했습니다. 

참고로 localhost:3000은 프런트엔드 개발자의 편의를 위해 잠시 열어두었습니다.

2021-04-26 08:23 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
> +        logger.info(categoryId + "번 카테고리의 best 메뉴 요청");
코멘트에 따라 템플릿에 맞춰서 수정했습니다~

2021-04-26 08:32 UTC, MJbae commented on BE/src/main/java/com/mj_eno/sidedish/service/DishService.java
> +    public final CategoryService categoryService;
다른 Service를 의존하여 구현한 이유는 DishService를 보기 좋게 만들기 위해서 입니다. 물론 다른 Service를 의존함에 따라 순환참조가 발생할 가능성이 있지만 현재의 설계에서 그러한 이슈가 발생할 수 없다고 판단했습니다. 
처음에는 7개의 Repository를 주입 받아서 구현했습니다. 그런데 DishService가 너무 비대해져 가독성이 떨어지는 코드가 되어서 위와 같이 수정하였습니다.

2021-04-29 01:35 UTC, merged