[Roach, noel] side-dish 2주차 Request
codesquad-members-2021/sidedish pull request #44
Opened 2021-04-27 05:44 UTC by tmdgusya

# 노을(Noel), Roach BE REVIEW

## 공통사항

- DB 에서 Image 의 관리? 일단은 String 으로 전부 집어넣고 Response 로는 List 로 주어야 하기에 DB 로 가져올때 ',' 구분으로 parsing 하여 List 로 치환해 주었는데, 이 부분이 옳은건지? 아니면 더 좋은 방법이 있는지 궁금합니다.

- 최대한 공식문서에 의거해서 한거 같은데, private 생성자 생성 등등.. Domain 객체가 최종 객체로 존재할 수 있게 하였습니다.

- Validate 는 아직 전체적으로 진행되고 있지는 않은 상태입니다. 틀만 잡아 놓은 상태라, 다음 리뷰 커밋때 적용될 것 같습니다.

- 현재 더미 데이터를 삽입할 때 POST 방식으로 제공되는 JSON을 받아서 쌓는 방식을 채택했는데, 서버내 파일로 저장해서 JSON을 읽는 방식 또는 다른 더 좋은 방법이 있을지? 궁금합니다.

- 아이템에 대한 모든 정보를 하나의 객체에서 담당하다 보니, API에 따라 가공의 이유로 일회성으로 DTO를 남발하고 있습니다. 현재 방식이 옳은 방식인지? 아니면 필요에 따라 객체를 분리해서 DTO를 최소화 시키는 것이 옳은 방식인지 궁금합니다.

- Error 구조는 Application 에서 발생하는 Exception 들은 최상단의 BusinessException 을 상속하도록 설계하였습니다.

## Repository 가 2개인 이유

- Category 는 Item 을 관리하는게 맞으나, Order 의 경우 User 가 관리하는 것이 맞다고 판단했습니다. 따라서 Order 는 UserRepository 를 통해 관리하는 구조로 설계하였습니다. 따라서 Application 의 구조는 아래와 같습니다.

- Category 가 Item 을 관리하고, UserRepository 에서 Order 를 관리합니다. Order 는 Item 과 N:1 관계이므로, 이는 Data JDBC 가 기능하는 지원이 아니므로, Foreign Key 로 해당 관계를 풀어낼 수 있도록 하였습니다.

2021-04-29 04:14 UTC, sanhee commented
✨ [API문서](https://documenter.getpostman.com/view/14857650/TzK17FHo#20a62557-0dc5-46b9-944d-141e5cf519a8) 추가 합니다!

2021-05-04 10:13 UTC, ksundong commented
안녕하세요! 로치, 노을!
리뷰가 늦어져서 죄송합니다!
곧 리뷰 시작하겠습니다~

2021-05-04 12:00 UTC, ksundong requested changes
안녕하세요~ Roach & 노을! 리뷰어 Dion입니다.
개인 사정으로 리뷰가 많이 늦어져 죄송합니다. 그리고 Roach는 살짝 염탐을 했더니 좋은 기회를 잡으신 것 같네요.
이 자리를 빌어 진심으로 축하드립니다. 🎉

이번 리뷰를 하면서 느낀 점은, 구현이 너무 바쁜 탓인지, 코드 퀄리티가 두분에게 기대했던 것 보다 낮았습니다.
좀 세게 말씀드리자면, 단순히 구현에 급급한 코드로 보입니다. 우리가 코드스쿼드에서 배울건 이런 구현능력이 아닙니다.
구현하는 능력도 중요하지만, 그것에 매몰되면 품질이 낮은 코드가 나오게됩니다. 그것을 경계하셨으면 좋겠습니다.
우리가 진정으로 길러야 하는 능력은 **지정된 기간내에 만족할 수 있을만큼의 품질로** 개발하는 능력이라고 개인적으로 생각해요.

제가 개인적으로 읽기 추천하는 책인 <소프트웨어 장인>에서 나오는 매니페스토입니다.

> 소프트웨어 장인을 열망하는 우리는, 스스로의 기술을 연마하고, 다른 사람들이 기술을 배울 수 있도록 도움으로써 프로페셔널 소프트웨어 개발의 수준을 높인다. 이러한 일을 하는 과정에서 우리는 다음과 같은 가치들을 추구한다.
> - 동작하는 소프트웨어뿐만 아니라, 정교하고 솜씨 있게 만들어진 작품을
> - 변화에 대응하는 것뿐만 아니라, 계속해서 가치를 더하는 것을
> - 개별적으로 협력하는 것뿐만 아니라, 프로페셔널 커뮤니티를 조성하는 것을
> - 고객과 협업하는 것뿐만 아니라, 생산적인 동반자 관계를

그래도 구현이 되고 정상적으로 동작은 했었을 것 같습니다. 동작하는 소프트웨어를 개발하는 것도 중요한 역량입니다.
코드퀄리티가 아무리 좋아봐야 동작하지 않으면 아무런 의미가 없으니까요.

그냥 먼저 코드스쿼드에 들어온 꼰대소리라고 가볍게 생각해주시면 감사하겠습니다.

## Q&A

- DB 에서 Image 의 관리? 일단은 String 으로 전부 집어넣고 Response 로는 List 로 주어야 하기에 DB 로 가져올때 ',' 구분으로 parsing 하여 List 로 치환해 주었는데, 이 부분이 옳은건지? 아니면 더 좋은 방법이 있는지 궁금합니다.

당연히 아닙니다. 저라면 Image 객체를 만들어줬을 것 같네요. 문자열 및 원시타입의 포장은 꽤 자주 써먹는 테크닉입니다.

- 최대한 공식문서에 의거해서 한거 같은데, private 생성자 생성 등등.. Domain 객체가 최종 객체로 존재할 수 있게 하였습니다.

최종 객체가 뭐죠? `final`을 의미하신건가요? 확실히 Spring Data JDBC는 불변객체를 추천하고 있습니다.
불변 객체의 활용은 좋은 시도라고 생각됩니다.

- Validate 는 아직 전체적으로 진행되고 있지는 않은 상태입니다. 틀만 잡아 놓은 상태라, 다음 리뷰 커밋때 적용될 것 같습니다.

Validation은 현재 단계에서 신경쓰기 쉽지 않은 영역이라고 생각됩니다. 차근차근 Refernce를 쌓아 주시면 좋을 것 같아요.

- 현재 더미 데이터를 삽입할 때 POST 방식으로 제공되는 JSON을 받아서 쌓는 방식을 채택했는데, 서버내 파일로 저장해서 JSON을 읽는 방식 또는 다른 더 좋은 방법이 있을지? 궁금합니다.

저 같은 경우에는 Mock API에서 응답된 Json을 SQL 스크립트로 만들어지도록 자바로 프로그래밍 했었습니다.

- 아이템에 대한 모든 정보를 하나의 객체에서 담당하다 보니, API에 따라 가공의 이유로 일회성으로 DTO를 남발하고 있습니다. 현재 방식이 옳은 방식인지? 아니면 필요에 따라 객체를 분리해서 DTO를 최소화 시키는 것이 옳은 방식인지 궁금합니다.

Domain 객체를 분리 하는 시도를 해보는 것이 좋고, DTO의 경우에는 요청용 DTO, 응답용 DTO, 레이어 이동을 위한 DTO를 다 구분해준 적도 있습니다.

- Error 구조는 Application 에서 발생하는 Exception 들은 최상단의 BusinessException 을 상속하도록 설계하였습니다.

개선의견을 코멘트에 남겼습니다.

---

> Category 는 Item 을 관리하는게 맞으나, Order 의 경우 User 가 관리하는 것이 맞다고 판단했습니다. 따라서 Order 는 UserRepository 를 통해 관리하는 구조로 설계하였습니다. 따라서 Application 의 구조는 아래와 같습니다.
> - Category 가 Item 을 관리하고, UserRepository 에서 Order 를 관리합니다. Order 는 Item 과 N:1 관계이므로, 이는 Data JDBC 가 기능하는 지원이 아니므로, Foreign Key 로 해당 관계를 풀어낼 수 있도록 하였습니다.

DDD는 어려운 영역이죠. 좋은 고민을 하신 것 같아요. 💯 

고생하셨습니다. 궁금하시거나 토론하고 싶은 부분이 있으시면 코멘트 남겨주세요~
두분 다 파이팅하세요~

2021-05-04 12:00 UTC, ksundong commented on iOS/sideDish/Constant.swift
> +}
PR 보내실 때 항상 리뷰 받고 싶은 부분만 올리도록 해주세요 ㅋㅋ

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiCategoryController.java
> +public class ApiCategoryController {
이 클래스는 API 재설계를 꼭 시도해보시면 좋을 것 같네요.
이게 최선은 아닐거라고 생각됩니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiCategoryController.java
> +        Category category = categoryService.findById(3L);
1,2,3 을 박아 놓는건 그리 좋은 선택이 아닌 것 같네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiCategoryController.java
> +        for (Long i = 1L; i < 4L; i++) {
불필요하게 리터럴이 너무 많이 선언되고 있네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiCategoryController.java
> +    public void addMainItems(@RequestBody List<ItemDto> itemDtoList) {
List를 Wrapping하는 DTO를 만들어줘도 좋을 것 같아요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiCategoryController.java
> +    }
불필요한 `ResponseEntity` 사용을 지양해주세요.
그리고, 디미터 법칙을 깨지 않는 형태로 구현해주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/ApiUserController.java
> +    }
음 뭘까요? 동작하는 코드 맞나요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Global 말고, SideDish는 어때요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/GlobalExceptionHandler.java
> +        final ErrorResponse from = ErrorResponse.from(errorCode);
from 맞나요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/controller/GlobalExceptionHandler.java
> +    }
동일한 처리를 해줄거라면 브라이언의 테코톡을 기억해봅시다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Category.java
> +    private Map<String, Item> items = new HashMap<>();
드디어 나왔네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Category.java
> +    }
새로 생성자 하나를 더 만들어서 null을 직접 인자로 안넘겨주는 식의 설계는 어떤가요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Category.java
> +            this.items.put(item.getId(), item);
this 빼도 괜찮을 것 같네요~

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Category.java
> +    }
좋네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Item.java
> +    private final String deliveryTypes;
Collection일 것 같은 이름인데, 단순 String인게 아쉽네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Item.java
> +        this.detailSection = detailSection;
생성자에 사용되는 인자가 많다고 생각해볼 수 있겠네요.
적절히 쪼개보는 연습해보셨으면 좋겠습니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Item.java
> +    }
이럴 때에는 정적 팩토리 메서드의 사용보다는
빌더 패턴의 적용이 좋다고 생각됩니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/Order.java
> +@Table(value = "ORDERS")
예약어로 인해서 테이블명이 변경되었군요 ㅠㅠ

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/domain/User.java
> +    }
User가 UserDTO를 알도록 하는 식의 설계는 예전부터 말씀드리지만 추천드리지 않습니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Category/ResponseDTO.java
> +public class ResponseDTO {
이 DTO는 필요한가요?
전 statusCode를 들고있는 식의 구현은 REST의 안티 패턴이라고 생각합니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Category/ResponseDTO.java
> +public class ResponseDTO {
그리고 Response라는 이름이 너무 추상적이어서 좀 더 구체적인 수준으로 바꿔줘도 괜찮을 것 같아요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Category/ResponseDTO.java
> +        List<Item> items = new ArrayList<>(category.getItems().values());
category에서 바로 Item List를 가져오는 구현을 생각해봐주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Category/ResponseDTO.java
> +        List<Item> items = new ArrayList<>(category.getItems().values());
public 메서드에서 new를 호출하는 걸 지양해주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Category/ResponseDTO.java
> +        List<ItemInfoDto> itemInfoDtos = items.stream().map(ItemInfoDto::of).collect(Collectors.toList());
위의 피드백을 반영하면 stream을 바로 열어도 되겠죠?
Stream의 사용은 좋습니다.
개행을 통해서 가독성을  높이는 식의 구현을 시도해봐주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Detail/RequestDataDto.java
> +    public String[] detail_section;
일단 네이밍 컨벤션이 지켜지지 않았네요. ㅠ
그리고, 전부 String으로 되어있는데, 좋지 않은 구현형태로 생각됩니다.
그리고, 가급적이면 배열의 사용을 자제해주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/Detail/RequestHashDto.java
> +}
응? 이건 어떤 용도인가요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/ItemInfoDto.java
> +    private final List<Badge> badges;
JsonProperty를 남발하는 것은 좋지 않다고 생각됩니다~

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/ItemInfoDto.java
> +    private final List<Badge> badges;
네이밍도 좋게 바꿔주는 연습을 해보세요~

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/ItemInfoDto.java
> +    }
개선해보면 좋을 것 같네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/SideDishInfoDto.java
> +        String deliveryFee = "2,500원 (40,000원 이상 구매 시 무료)";
구현이 급해서 그랬을거라고 생각하겠습니다. 😭

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/dto/UserDto.java
> +    @Pattern(regexp = "^[a-zA-Z@.]")
좋네요. 사실 이메일은 이정도 Regex로는 안되고
그냥 JSR-380 BeanValidation을 사용하셨으니 `@Email`을 사용해볼까요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/error/ErrorCode.java
> +public enum ErrorCode {
👍

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/error/ErrorResponse.java
> +    private LocalDateTime time;
시간을 주는 구현 한 번 생각해볼만 하네요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/error/ErrorResponse.java
> +    }
빌더패턴 적용 좋습니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/error/FieldError.java
> +public class FieldError {
이름이 겹치니 다른 이름 생각해보는 것도 좋을 것 같아요~

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/error/exception/BusinessException.java
> +    }
예외 포장용 생성자도 하나 만들어주시고
`String message`를 인자로 받는 것도 만들어주는건 어떨까요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/repository/CategoryRepository.java
> +    List<Category> findAll();
Override 된 메서드 아닌가요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/repository/CategoryRepository.java
> +    List<Category> findAll();
`@Override` 꼭 붙여주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(NoSuchFieldError::new);
NoSuchField맞나요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/service/CategoryService.java
> +                    ""
하드 코딩하니까 뭔지 하나도 모르겠어요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/service/CategoryService.java
> +        for (ItemDto itemDto : itemDtoList) {
stream을 이용해보는건 어떨까요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/service/UserService.java
> +    public User login(UserDto userDto) {
User 줄 필요가 있나요?

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/Badge.java
> +    정상가(1), 론칭특가(0.1), 이벤트특가(0.2);
한글 사용은 지양합시다 ㅎㅎ
```suggestion
    정상가(1),
    론칭특가(0.1),
    이벤트특가(0.2);
```

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/Badge.java
> +    정상가(1), 론칭특가(0.1), 이벤트특가(0.2);
그리고 Lambda를 활용하면 Enum에 로직을 넣을 수도 있을겁니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/Convert.java
> +public class Convert {
동사를 클래스 이름으로 사용하는건 지양해주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/Convert.java
> +public class Convert {
유틸리티성 클래스라면 인스턴스를 생성할 수 없도록 해주세요.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/Convert.java
> +public class Convert {
그리고 어떤 Convert를 담당하는지를 표현해주면 좋을 것 같네요.
아래의 두 메서드는 분리가 필요해보입니다.

2021-05-04 12:00 UTC, ksundong commented on src/main/java/com/example/util/builder/DeliveryInfoBuilder.java
> +public class DeliveryInfoBuilder {
View용 객체를 조립하는 역할을 해주고 있네요.
좋은 것 같습니다.

2021-05-04 12:00 UTC, ksundong commented on src/test/java/com/example/repository/CategoryRepositoryTest.java
> +@SpringBootTest
이 애노테이션은 Repository 테스트용이 아닙니다.
더 찾아보세요!

2021-05-04 12:00 UTC, ksundong commented on src/test/java/com/example/repository/CategoryRepositoryTest.java
> +    }
사실 Repository의 동작을 테스트하는건 거의 무의미하다고 봅니다.
스프링 구현체의 동작을 학습용도로 시험하는 건가요? 그럼 의미가 있습니다.

좀 더 상세하게 리뷰하자면, 우리가 테스트해야 할 범위는 우리가 작성한 코드에서부터 시작해야합니다.

2021-05-04 12:00 UTC, ksundong commented on src/test/java/com/example/repository/OrderTest.java
> +class OrderTest {
이름만 보면 단위테스트인데 통합테스트를 하고있네요.

2021-05-04 12:00 UTC, ksundong commented on src/test/java/com/example/util/builder/DeliveryInfoBuilderTest.java
> +    }
테스트가 아니네요 ㅠㅠ
assertion을 추가해봅시다.

2022-05-25 23:04 UTC, closed without merging